"""Optimization pack instructional chrome + fallback prose follow UI/content locale."""

from __future__ import annotations

from types import SimpleNamespace

from services.artifacts import (
    build_optimization_pack,
    build_robots_txt,
    build_unified_fix_html,
    fallback_llms_txt,
    unified_fix_html_from_entity,
)
from services.mailer import build_pack_email
from services.pack_i18n import content_locale, resolve_pack_locales, t


def test_content_locale_prefers_supported_scraped_lang():
    assert content_locale(scraped_lang="ko-KR", ui_locale="en") == "ko"
    assert content_locale(scraped_lang="fr", ui_locale="de") == "de"
    ui, content = resolve_pack_locales(
        ui_locale="zh", scraped={"lang": "en-US"}
    )
    assert ui == "zh"
    assert content == "en"


def test_unified_html_native_titles_per_locale():
    for loc, needle in (
        ("it", "Pack ottimizzazione"),
        ("en", "Optimization pack"),
        ("de", "Optimierungspaket"),
        ("es", "Paquete de optimización"),
        ("zh", "优化包"),
        ("ko", "최적화 팩"),
    ):
        html = build_unified_fix_html(
            url="https://acme.example/",
            domain="acme.example",
            llms_txt="# Acme",
            robots_txt="User-agent: *\nAllow: /\n",
            findings=[
                {
                    "severity": "critical",
                    "title": "llms.txt assente",
                    "detail": "manca in root",
                }
            ],
            aio_score=41,
            geo_score=38,
            locale=loc,
        )
        assert needle in html
        assert f'lang="{loc}"' in html
        assert 'id="head-fix"' in html
        assert "# Acme" in html


def test_fallback_llms_and_robots_follow_locale():
    scraped = {
        "domain": "acme.example",
        "title": "Acme",
        "description": "",
        "lang": "de",
        "links": [],
        "headings": [],
        "pages_analyzed": 1,
    }
    llms = fallback_llms_txt("https://acme.example/", scraped, locale="en")
    assert "Offizielle Website von Acme" in llms
    robots = build_robots_txt("https://acme.example/", scraped, locale="en")
    assert "Draft robots.txt generated by Centropic" in robots


def test_build_pack_english_chrome():
    scraped = {
        "domain": "acme.example",
        "title": "Acme",
        "description": "Hello world site",
        "lang": "en",
        "links": [],
        "headings": ["Products"],
        "pages_analyzed": 2,
    }
    pack = build_optimization_pack(
        "https://acme.example/",
        scraped,
        api_key="",
        findings=[
            {
                "severity": "critical",
                "title": "llms.txt assente",
                "detail": "manca",
            }
        ],
        result={"aio_score": 40, "geo_score": 42},
        locale="en",
    )
    html = pack["centropic-fix.html"]
    assert "Optimization pack" in html
    assert "Issues to close" in html
    assert "Recommended priorities" in pack["fix-this-week.md"]
    assert "Draft robots.txt" in pack["robots.txt"]
    assert "Official site for Acme" in pack["llms.txt"] or "Hello world site" in pack[
        "llms.txt"
    ]


def test_download_rebuild_uses_ui_locale():
    entity = SimpleNamespace(
        domain="brand.io",
        url="https://brand.io/",
        llms_txt="HELLO_LLMS",
        json_ld_artifact="ORG_LD",
        faq_artifact="",
        meta_pack_artifact="META_X",
        robots_artifact="User-agent: *\nAllow: /\n",
        checklist_artifact="OLD_IT_CHECK",
        before_after_artifact="OLD_IT_BA",
        findings=[
            {
                "severity": "critical",
                "title": "llms.txt assente",
                "detail": "manca",
            }
        ],
        aio_score=70,
        geo_score=65,
    )
    html = unified_fix_html_from_entity(entity, locale="ko")
    assert "최적화 팩" in html
    assert "HELLO_LLMS" in html
    assert "OLD_IT_CHECK" not in html
    assert t("checklist_intro", "ko") in html


def test_pack_email_locale():
    subject, text, html = build_pack_email(
        user_name="Ada Lovelace",
        domain="acme.example",
        aio_score=50,
        geo_score=55,
        locale="en",
    )
    assert "optimization pack" in subject.lower()
    assert "Hi Ada" in text
    assert "optimization pack" in html.lower()
