"""Pack llms.txt branding and Important pages filtering."""

from __future__ import annotations

from services.artifacts import (
    _clean_brand_name,
    _important_page_lines,
    _sanitize_generated_llms,
    fallback_llms_txt,
)


def test_clean_brand_centropic():
    assert _clean_brand_name("centropic.ai", "Signal Intelligence") == "Centropic"
    assert _clean_brand_name("www.centropic.ai", None) == "Centropic"


def test_important_pages_drop_404_and_rewrite_pricing():
    lines = _important_page_lines(
        [
            "404 Not Found -> https://centropic.ai/pricing",
            {"title": "Prezzi", "url": "https://centropic.ai/prezzi", "status_code": 200},
            {
                "title": "Broken",
                "url": "https://centropic.ai/x",
                "status_code": 500,
            },
            "Status — Centropic -> https://centropic.ai/status",
            # Successful-looking legacy alias still rewritten for Centropic only.
            {
                "title": "https://centropic.ai/pricing",
                "url": "https://centropic.ai/pricing",
                "status_code": 200,
            },
            # Other domains keep /pricing.
            {
                "title": "Pricing",
                "url": "https://example.com/pricing",
                "status_code": 200,
            },
        ]
    )
    joined = "\n".join(lines)
    assert "404" not in joined
    assert "centropic.ai/pricing" not in joined
    assert "https://centropic.ai/prezzi" in joined
    assert "https://centropic.ai/status" in joined
    assert "https://example.com/pricing" in joined
    assert "500" not in joined


def test_fallback_llms_uses_centropic_branding():
    text = fallback_llms_txt(
        "https://centropic.ai/",
        {
            "domain": "centropic.ai",
            "title": "Signal Intelligence per AIO e GEO · centropic.ai",
            "description": "Diagnosi del dominio.",
            "headings": ["Stimato e Misurato, sempre distinti", "Tre fasi."],
            "links": [
                "404 Not Found -> https://centropic.ai/pricing",
                "FAQ -> https://centropic.ai/faq",
            ],
            "pages_analyzed": 23,
        },
    )
    assert text.startswith("# Centropic")
    assert "GeoPulse" not in text
    assert "geopulse.it" not in text
    assert "Centropic (centropic.ai)" in text
    assert "404" not in text
    assert "centropic.ai/pricing" not in text
    assert "sempre distinti" not in text
    assert "restano distinti" in text
    assert "Pagine analizzate da Centropic" in text


def test_sanitize_strips_legacy_generator():
    raw = (
        "# x\n"
        "- 404 Not Found -> https://centropic.ai/pricing\n"
        "- https://centropic.ai/pricing -> https://centropic.ai/pricing\n"
        "_Generated by GeoPulse (geopulse.it) on 2026-08-04_\n"
    )
    out = _sanitize_generated_llms(raw)
    assert "404" not in out
    assert "GeoPulse" not in out
    assert "Centropic (centropic.ai)" in out
    assert "centropic.ai/pricing" not in out
    assert "centropic.ai/prezzi" in out
