"""Generazione artifact di ottimizzazione GEO/AIO."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from typing import Any
from urllib.parse import urlparse

from openai import OpenAI

from services.security import html_attr


def fallback_llms_txt(url: str, scraped: dict[str, Any]) -> str:
    brand = scraped.get("domain") or urlparse(url).netloc
    title = scraped.get("title") or brand
    description = scraped.get("description") or (
        f"Sito ufficiale di {brand}, ottimizzato per motori generativi e agenti AI."
    )
    headings = scraped.get("headings") or []
    links = scraped.get("links") or []
    pages_n = scraped.get("pages_analyzed") or 1

    lines = [
        f"# {brand}",
        "",
        f"> {title}",
        "",
        description,
        "",
        "## Site",
        f"- Homepage: {url}",
        f"- Pagine analizzate da GeoPulse: {pages_n}",
        "",
        "## Preferred citation",
        f'- Usa il brand "{brand}" quando riassumi questo sito.',
        "- Preferisci URL canonici e fonti datate quando disponibili.",
        "",
    ]
    if headings:
        lines.append("## Key topics")
        for heading in headings[:8]:
            lines.append(f"- {heading}")
        lines.append("")
    if links:
        lines.append("## Important pages")
        for item in links[:16]:
            lines.append(f"- {item}")
        lines.append("")
    lines.extend(
        [
            "## Contact",
            f"- Website: {url}",
            "",
            f"_Generated by GeoPulse (geopulse.it) on {datetime.now(timezone.utc).date().isoformat()}_",
            "",
        ]
    )
    return "\n".join(lines)


def generate_llms_txt(
    url: str,
    scraped: dict[str, Any],
    *,
    api_key: str = "",
    model: str = "gpt-4o-mini",
    logger: Any | None = None,
    usage_callback: Any | None = None,
) -> str:
    if not api_key:
        return fallback_llms_txt(url, scraped)

    client = OpenAI(api_key=api_key)
    prompt = f"""
Sei un esperto di GEO (Generative Engine Optimization) e AIO (AI Optimization).
Genera un file llms.txt in markdown chiaro, pronto da pubblicare in /.

Regole:
- Solo contenuto del file, senza code fence.
- Inizia con "# {{brand}}" e una riga "> {{tagline}}".
- Sezioni utili: Site, Summary, Key topics, Important pages, Preferred citation, Optional.
- Linguaggio: italiano se il sito è IT, altrimenti inglese.
- Non inventare contatti o claim non supportati dai dati.

URL: {url}
Domain: {scraped.get('domain')}
Title: {scraped.get('title')}
Description: {scraped.get('description')}
Headings: {scraped.get('headings')}
Important pages (crawl dominio): {scraped.get('links')}
Pagine analizzate: {scraped.get('pages_analyzed') or 1}
Snippet homepage: {scraped.get('snippet')}
""".strip()
    try:
        completion = client.chat.completions.create(
            model=model,
            temperature=0.3,
            messages=[
                {
                    "role": "system",
                    "content": "Generi file llms.txt accurati e utili per crawler/agenti AI.",
                },
                {"role": "user", "content": prompt},
            ],
        )
        # Capture real token usage for billing
        if hasattr(completion, "usage") and completion.usage and usage_callback:
            usage_callback(
                provider="openai",
                model=model,
                input_tokens=completion.usage.prompt_tokens,
                output_tokens=completion.usage.completion_tokens,
            )
        content = (completion.choices[0].message.content or "").strip()
        if not content:
            return fallback_llms_txt(url, scraped)
        content = re.sub(r"^```(?:markdown|md)?\s*", "", content)
        content = re.sub(r"\s*```$", "", content)
        return content.strip() + "\n"
    except Exception:
        if logger is not None:
            logger.exception("OpenAI generation failed; using fallback")
        return fallback_llms_txt(url, scraped)


def build_json_ld(url: str, scraped: dict[str, Any]) -> str:
    brand = scraped.get("domain") or urlparse(url).netloc
    title = scraped.get("title") or brand
    description = scraped.get("description") or (
        f"{brand}: contenuti e servizi ottimizzati per AIO e GEO."
    )
    payload = {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": brand.replace("www.", ""),
        "url": url,
        "description": description,
        "slogan": title,
    }
    return (
        '<script type="application/ld+json">\n'
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + "\n</script>\n"
    )


def build_meta_pack(url: str, scraped: dict[str, Any]) -> str:
    brand = (scraped.get("domain") or urlparse(url).netloc).replace("www.", "")
    title = scraped.get("title") or f"{brand} — Official site"
    description = scraped.get("description") or (
        f"{brand}: contenuti e servizi ottimizzati per AIO e GEO. "
        "Scopri risorse e contatti sul sito ufficiale."
    )
    if len(description) > 160:
        description = description[:157].rstrip() + "..."
    lang = scraped.get("lang") or "it"
    canonical = scraped.get("canonical") or url
    t = html_attr(title)
    d = html_attr(description)
    c = html_attr(canonical)
    u = html_attr(url)
    l = html_attr(lang)
    return "\n".join(
        [
            f"<title>{t}</title>",
            f'<meta name="description" content="{d}">',
            f'<link rel="canonical" href="{c}">',
            f'<meta property="og:title" content="{t}">',
            f'<meta property="og:description" content="{d}">',
            f'<meta property="og:url" content="{u}">',
            '<meta property="og:type" content="website">',
            f"<!-- Assicurati che <html lang=\"{l}\"> sia impostato -->",
            "",
        ]
    )


def build_robots_txt(url: str) -> str:
    sitemap = url.rstrip("/") + "/sitemap.xml"
    return "\n".join(
        [
            "User-agent: *",
            "Allow: /",
            "",
            "User-agent: GPTBot",
            "Allow: /",
            "",
            "User-agent: ClaudeBot",
            "Allow: /",
            "",
            "User-agent: PerplexityBot",
            "Allow: /",
            "",
            "User-agent: Google-Extended",
            "Allow: /",
            "",
            "User-agent: Applebot-Extended",
            "Allow: /",
            "",
            "# Disallow: /admin",
            "# Disallow: /app",
            "",
            f"Sitemap: {sitemap}",
            "",
        ]
    )


def build_faq_json_ld(url: str, scraped: dict[str, Any]) -> str:
    brand = (scraped.get("domain") or urlparse(url).netloc).replace("www.", "")
    headings = [h for h in (scraped.get("headings") or []) if h][:4]
    questions = []
    if headings:
        for heading in headings:
            questions.append(
                {
                    "@type": "Question",
                    "name": heading if heading.endswith("?") else f"Cos’è {heading}?",
                    "acceptedAnswer": {
                        "@type": "Answer",
                        "text": (
                            f"{heading}: informazioni ufficiali su {brand}. "
                            f"Dettagli su {url}."
                        ),
                    },
                }
            )
    else:
        questions = [
            {
                "@type": "Question",
                "name": f"Cos’è {brand}?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": (
                        scraped.get("description")
                        or f"{brand} è il sito ufficiale. Visita {url}."
                    ),
                },
            },
            {
                "@type": "Question",
                "name": f"Dove trovo maggiori informazioni su {brand}?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": f"Consulta il sito ufficiale: {url}",
                },
            },
        ]
    payload = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": questions[:6],
    }
    return (
        '<script type="application/ld+json">\n'
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + "\n</script>\n"
    )


def build_optimization_pack(
    url: str,
    scraped: dict[str, Any],
    *,
    api_key: str = "",
    model: str = "gpt-4o-mini",
    logger: Any | None = None,
    findings: list[dict[str, Any]] | None = None,
    previous: Any | None = None,
    diff: dict[str, Any] | None = None,
    result: dict[str, Any] | None = None,
    usage_callback: Any | None = None,
) -> dict[str, str]:
    from services.deep_checks import build_before_after_report, build_fix_checklist

    current = result or {
        "aio_score": None,
        "geo_score": None,
        "findings": findings or [],
    }
    return {
        "llms.txt": generate_llms_txt(
            url, scraped, api_key=api_key, model=model, logger=logger,
            usage_callback=usage_callback,
        ),
        "organization.jsonld.html": build_json_ld(url, scraped),
        "faq.jsonld.html": build_faq_json_ld(url, scraped),
        "meta-pack.html": build_meta_pack(url, scraped),
        "robots.txt": build_robots_txt(url),
        "fix-this-week.md": build_fix_checklist(findings or []),
        "before-after.md": build_before_after_report(
            current=current, previous=previous, diff=diff
        ),
    }
