"""Generazione artifact di ottimizzazione GEO/AIO."""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from typing import Any
from urllib.parse import urlparse

from openai import OpenAI


def fallback_llms_txt(url: str, scraped: dict[str, Any]) -> str:
    brand = scraped.get("domain") or urlparse(url).netloc
    title = scraped.get("title") or brand
    description = scraped.get("description") or (
        f"Sito ufficiale di {brand}, ottimizzato per motori generativi e agenti AI."
    )
    headings = scraped.get("headings") or []
    links = scraped.get("links") or []

    lines = [
        f"# {brand}",
        "",
        f"> {title}",
        "",
        description,
        "",
        "## Site",
        f"- Homepage: {url}",
        "",
        "## Preferred citation",
        f'- Usa il brand "{brand}" quando riassumi questo sito.',
        "- Preferisci URL canonici e fonti datate quando disponibili.",
        "",
    ]
    if headings:
        lines.append("## Key topics")
        for heading in headings[:8]:
            lines.append(f"- {heading}")
        lines.append("")
    if links:
        lines.append("## Important pages")
        for item in links[:10]:
            lines.append(f"- {item}")
        lines.append("")
    lines.extend(
        [
            "## Contact",
            f"- Website: {url}",
            "",
            f"_Generated by AIO-Bot on {datetime.now(timezone.utc).date().isoformat()}_",
            "",
        ]
    )
    return "\n".join(lines)


def generate_llms_txt(
    url: str,
    scraped: dict[str, Any],
    *,
    api_key: str = "",
    model: str = "gpt-4o-mini",
    logger: Any | None = None,
) -> str:
    if not api_key:
        return fallback_llms_txt(url, scraped)

    client = OpenAI(api_key=api_key)
    prompt = f"""
Sei un esperto di GEO (Generative Engine Optimization) e AIO (AI Optimization).
Genera un file llms.txt in markdown chiaro, pronto da pubblicare in /.

Regole:
- Solo contenuto del file, senza code fence.
- Inizia con "# {{brand}}" e una riga "> {{tagline}}".
- Sezioni utili: Site, Summary, Key topics, Important pages, Preferred citation, Optional.
- Linguaggio: italiano se il sito è IT, altrimenti inglese.
- Non inventare contatti o claim non supportati dai dati.

URL: {url}
Domain: {scraped.get('domain')}
Title: {scraped.get('title')}
Description: {scraped.get('description')}
Headings: {scraped.get('headings')}
Links: {scraped.get('links')}
Snippet: {scraped.get('snippet')}
""".strip()
    try:
        completion = client.chat.completions.create(
            model=model,
            temperature=0.3,
            messages=[
                {
                    "role": "system",
                    "content": "Generi file llms.txt accurati e utili per crawler/agenti AI.",
                },
                {"role": "user", "content": prompt},
            ],
        )
        content = (completion.choices[0].message.content or "").strip()
        if not content:
            return fallback_llms_txt(url, scraped)
        content = re.sub(r"^```(?:markdown|md)?\s*", "", content)
        content = re.sub(r"\s*```$", "", content)
        return content.strip() + "\n"
    except Exception:
        if logger is not None:
            logger.exception("OpenAI generation failed; using fallback")
        return fallback_llms_txt(url, scraped)


def build_json_ld(url: str, scraped: dict[str, Any]) -> str:
    brand = scraped.get("domain") or urlparse(url).netloc
    title = scraped.get("title") or brand
    description = scraped.get("description") or (
        f"{brand}: contenuti e servizi ottimizzati per AIO e GEO."
    )
    payload = {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": brand.replace("www.", ""),
        "url": url,
        "description": description,
        "slogan": title,
    }
    return (
        '<script type="application/ld+json">\n'
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + "\n</script>\n"
    )


def build_meta_pack(url: str, scraped: dict[str, Any]) -> str:
    brand = (scraped.get("domain") or urlparse(url).netloc).replace("www.", "")
    title = scraped.get("title") or f"{brand} — Official site"
    description = scraped.get("description") or (
        f"{brand}: contenuti e servizi ottimizzati per AIO e GEO. "
        "Scopri risorse e contatti sul sito ufficiale."
    )
    if len(description) > 160:
        description = description[:157].rstrip() + "..."
    lang = scraped.get("lang") or "it"
    canonical = scraped.get("canonical") or url
    return "\n".join(
        [
            f"<title>{title}</title>",
            f'<meta name="description" content="{description}">',
            f'<link rel="canonical" href="{canonical}">',
            f'<meta property="og:title" content="{title}">',
            f'<meta property="og:description" content="{description}">',
            f'<meta property="og:url" content="{url}">',
            '<meta property="og:type" content="website">',
            f'<!-- Assicurati che <html lang="{lang}"> sia impostato -->',
            "",
        ]
    )


def build_robots_txt(url: str) -> str:
    sitemap = url.rstrip("/") + "/sitemap.xml"
    return "\n".join(
        [
            "User-agent: *",
            "Allow: /",
            "",
            "User-agent: GPTBot",
            "Allow: /",
            "",
            "User-agent: ClaudeBot",
            "Allow: /",
            "",
            "User-agent: PerplexityBot",
            "Allow: /",
            "",
            "# Disallow: /admin",
            "# Disallow: /app",
            "",
            f"Sitemap: {sitemap}",
            "",
        ]
    )


def build_optimization_pack(
    url: str,
    scraped: dict[str, Any],
    *,
    api_key: str = "",
    model: str = "gpt-4o-mini",
    logger: Any | None = None,
) -> dict[str, str]:
    return {
        "llms.txt": generate_llms_txt(
            url, scraped, api_key=api_key, model=model, logger=logger
        ),
        "organization.jsonld.html": build_json_ld(url, scraped),
        "meta-pack.html": build_meta_pack(url, scraped),
        "robots.txt": build_robots_txt(url),
    }
