"""Safe auto-apply: solo azioni allowlistate, piano Plus.

Azioni consentite:
- write_public_file: llms.txt | robots.txt | ai.txt
- inject_head: JSON-LD Organization/FAQ, meta-pack, viewport
- update_meta: title / description / canonical / og (strutturato)

Niente rewrite contenuti, redirect massivi, cambi theme/URL.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import re
import secrets
from datetime import datetime, timezone
from typing import Any
from urllib.parse import urlparse

SAFE_FILE_NAMES = frozenset({"llms.txt", "robots.txt", "ai.txt"})
SAFE_HEAD_IDS = frozenset(
    {
        "organization_jsonld",
        "faq_jsonld",
        "meta_pack",
        "viewport",
    }
)
SAFE_META_KEYS = frozenset(
    {"title", "description", "canonical", "og_title", "og_description", "og_url", "lang"}
)
TOKEN_PREFIX = "gp_live_"


def generate_apply_token() -> str:
    return TOKEN_PREFIX + secrets.token_urlsafe(32)


def hash_apply_token(token: str) -> str:
    return hashlib.sha256((token or "").encode("utf-8")).hexdigest()


def token_looks_valid(token: str) -> bool:
    return bool(token) and token.startswith(TOKEN_PREFIX) and len(token) >= 40


def verify_apply_token(token: str, token_hash: str) -> bool:
    if not token_looks_valid(token) or not token_hash:
        return False
    return hmac.compare_digest(hash_apply_token(token), token_hash)


def _snippet(text: str, limit: int = 180) -> str:
    clean = re.sub(r"\s+", " ", (text or "").strip())
    if len(clean) <= limit:
        return clean
    return clean[: limit - 1].rstrip() + "…"


def _ai_txt_fallback(url: str, scraped: dict[str, Any]) -> str:
    brand = (scraped.get("domain") or urlparse(url).netloc).replace("www.", "")
    return "\n".join(
        [
            f"# AI policy — {brand}",
            "",
            f"Site: {url}",
            f"Preferred source: {url.rstrip('/')}/llms.txt",
            "Contact: use the official website contact channels.",
            "Allow helpful summarization with citation of the canonical URL.",
            "",
            "_Generated by GeoPulse safe-apply_",
            "",
        ]
    )


def _viewport_tag() -> str:
    return '<meta name="viewport" content="width=device-width, initial-scale=1">'


def build_safe_actions(
    *,
    analysis: Any,
    pack: dict[str, str] | None = None,
) -> dict[str, Any]:
    """Costruisce il manifesto azioni sicure da un SiteAnalysis (o dict-like)."""
    pack = pack or {}
    url = getattr(analysis, "url", None) or ""
    domain = getattr(analysis, "domain", None) or urlparse(url).netloc
    artifacts: dict[str, Any] = {}
    if hasattr(analysis, "pack_artifacts"):
        artifacts = dict(analysis.pack_artifacts or {})
    signals: dict[str, Any] = {}
    if hasattr(analysis, "signals"):
        signals = dict(analysis.signals or {})
    scraped_hints = {
        "domain": domain,
        "title": getattr(analysis, "page_title", None) or domain,
    }

    llms = pack.get("llms.txt") or getattr(analysis, "llms_txt", None) or ""
    robots = pack.get("robots.txt") or getattr(analysis, "robots_artifact", None) or ""
    org = (
        pack.get("organization.jsonld.html")
        or getattr(analysis, "json_ld_artifact", None)
        or ""
    )
    faq = pack.get("faq.jsonld.html") or getattr(analysis, "faq_artifact", None) or ""
    meta = (
        pack.get("meta-pack.html")
        or getattr(analysis, "meta_pack_artifact", None)
        or ""
    )
    patches = str(artifacts.get("html-patches.html") or "")
    ai_txt = str(artifacts.get("ai.txt") or _ai_txt_fallback(url, scraped_hints))

    findings: list[dict[str, Any]] = []
    if hasattr(analysis, "findings"):
        findings = list(analysis.findings or [])
    finding_titles = {str(f.get("title") or "") for f in findings}

    actions: list[dict[str, Any]] = []

    def add_file(name: str, content: str, reason: str) -> None:
        if name not in SAFE_FILE_NAMES:
            return
        body = (content or "").strip()
        if not body:
            return
        actions.append(
            {
                "id": f"file:{name}",
                "type": "write_public_file",
                "path": f"/{name}",
                "content": body if body.endswith("\n") else body + "\n",
                "reason": reason,
                "safe": True,
            }
        )

    def add_head(action_id: str, html: str, reason: str) -> None:
        if action_id not in SAFE_HEAD_IDS:
            return
        body = (html or "").strip()
        if not body:
            return
        actions.append(
            {
                "id": f"head:{action_id}",
                "type": "inject_head",
                "head_id": action_id,
                "html": body if body.endswith("\n") else body + "\n",
                "reason": reason,
                "safe": True,
            }
        )

    if llms:
        add_file("llms.txt", llms, "Pubblica llms.txt per crawler/agenti AI")
    if robots:
        add_file(
            "robots.txt",
            robots,
            "Allinea robots.txt con Allow per bot AI + Sitemap",
        )

    adv = (signals.get("advanced") or {}) if isinstance(signals, dict) else {}
    ai_quality = adv.get("ai_txt_quality")
    if ai_quality in {None, "missing", "poor"} or any(
        "ai.txt" in t for t in finding_titles
    ):
        add_file("ai.txt", ai_txt, "Pubblica ai.txt con policy e link a llms.txt")

    if org:
        add_head(
            "organization_jsonld",
            org,
            "Inietta Organization JSON-LD in <head>",
        )
    if faq:
        add_head("faq_jsonld", faq, "Inietta FAQPage JSON-LD in <head>")
    if meta:
        add_head("meta_pack", meta, "Applica meta description/canonical/Open Graph")
    if any("Viewport" in t for t in finding_titles) or "viewport" in patches.lower():
        add_head("viewport", _viewport_tag(), "Aggiungi meta viewport mobile")

    meta_fields: dict[str, str] = {}
    title_m = re.search(r"<title>(.*?)</title>", meta, re.I | re.S)
    if title_m:
        meta_fields["title"] = title_m.group(1).strip()
    desc_m = re.search(
        r'<meta\s+name=["\']description["\']\s+content=["\'](.*?)["\']',
        meta,
        re.I | re.S,
    )
    if desc_m:
        meta_fields["description"] = desc_m.group(1).strip()
    canon_m = re.search(
        r'<link\s+rel=["\']canonical["\']\s+href=["\'](.*?)["\']',
        meta,
        re.I | re.S,
    )
    if canon_m:
        meta_fields["canonical"] = canon_m.group(1).strip()
    og_title = re.search(
        r'<meta\s+property=["\']og:title["\']\s+content=["\'](.*?)["\']',
        meta,
        re.I | re.S,
    )
    if og_title:
        meta_fields["og_title"] = og_title.group(1).strip()
    og_desc = re.search(
        r'<meta\s+property=["\']og:description["\']\s+content=["\'](.*?)["\']',
        meta,
        re.I | re.S,
    )
    if og_desc:
        meta_fields["og_description"] = og_desc.group(1).strip()
    if meta_fields:
        actions.append(
            {
                "id": "meta:homepage",
                "type": "update_meta",
                "target": "homepage",
                "fields": {k: v for k, v in meta_fields.items() if k in SAFE_META_KEYS},
                "reason": "Aggiorna meta homepage via API CMS",
                "safe": True,
            }
        )

    seen: set[str] = set()
    unique: list[dict[str, Any]] = []
    for action in actions:
        aid = str(action.get("id") or "")
        if aid in seen:
            continue
        seen.add(aid)
        unique.append(action)

    return {
        "version": 1,
        "safe_only": True,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "site": {
            "url": url,
            "domain": domain,
            "aio_score": getattr(analysis, "aio_score", None),
            "geo_score": getattr(analysis, "geo_score", None),
        },
        "actions": unique,
        "action_count": len(unique),
        "summary": [
            {
                "id": a.get("id"),
                "type": a.get("type"),
                "reason": a.get("reason"),
                "preview": _snippet(
                    a.get("path")
                    or a.get("head_id")
                    or json.dumps(a.get("fields") or {}, ensure_ascii=False)
                ),
            }
            for a in unique
        ],
        "excluded": [
            "rewrite contenuti lunghi",
            "redirect massivi",
            "cambio struttura URL",
            "modifiche theme invasive",
        ],
    }


def filter_ack_results(results: list[dict[str, Any]]) -> list[dict[str, Any]]:
    cleaned: list[dict[str, Any]] = []
    for item in results or []:
        if not isinstance(item, dict):
            continue
        action_id = str(item.get("id") or "")
        status = str(item.get("status") or "").lower()
        if not action_id or status not in {"ok", "skipped", "error"}:
            continue
        cleaned.append(
            {
                "id": action_id[:120],
                "status": status,
                "detail": str(item.get("detail") or "")[:300],
            }
        )
    return cleaned[:40]


def render_agent_template(
    template_path: str,
    *,
    api_base: str,
    site_id: int,
    token: str,
) -> str:
    with open(template_path, encoding="utf-8") as fh:
        raw = fh.read()
    return (
        raw.replace("{{API_BASE}}", api_base.rstrip("/"))
        .replace("{{SITE_ID}}", str(int(site_id)))
        .replace("{{TOKEN}}", token)
    )
